---
abstract: 'Handy Perl interface to ITRS Geneos XML-RPC Instrumentation API'
author:
  - 'Ivan Dmitriev <tot@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geneos-API
no_index:
  directory:
    - t
    - inc
requires:
  LWP::UserAgent: 6.04
  XML::LibXML: 1.97
version: 0.11
